config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'

  devise_for :users, :controllers => {registrations: "registrations"} # Makes the 1st time redirect magic work

  resources :activities
  resources :comments
  resources :users

  get '/profile', to: 'users#profile', as: :profile
  get '/edit_profile', to: 'users#edit#profile', as: :edit_profile

end

app/models/activity.rb
class Activity < ActiveRecord::Base
	has_many:comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :activity
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :activities
	has_many :comments
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
	before_action :find_activity, only: [:show, :edit, :update, :destroy]
  def index
  	@activity = Activity.all
  end

  def show

  end

  def edit

  end

  def create
  	@activity = Activity.new(user_params)

	  if @activity.save
	    redirect_to @activity
	  else
	    render 'new'
	  end
	end

	def new
		@activity = Activity.new
	end

	def update

 
	  if @activity.update(article_params)
	    redirect_to @activity
	  else
	    render 'edit'
	  end
	end

	def destroy
		@activity.destroy method: :delete

		redirect_to users_path
	end

  private

  def user_params
  	params.require(:activity).permit(:first_name, :last_name, :description)
  end

  def find_activity
  	@activity = Activity.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
  	@comment = comment.all
  end

  def show
  	@comment = comment.find(params[:id])
  end

  def edit
  	@comment = comment.find(params[:id])
  end

  def create
  	@comment = comment.new(user_params)

	  if @comment.save
	    redirect_to @comment
	  else
	    render 'new'
	  end
	end

	def new
		@comment = comment.new
	end

	def update
	  @comment = comment.find(params[:id])
 
	  if @comment.update(article_params)
	    redirect_to @comment
	  else
	    render 'edit'
	  end
	end

	def destroy
		@comment = comment.find(params[:id])
		@comment.destroy method: :delete

		redirect_to users_path
	end

  private

  def user_params
  	params.require(:comment).permit(:first_name, :last_name, :description)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	protected
  
  def after_sign_up_path_for(resource)
    :profile
  end

 

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  	@user = User.all
  end

  def show
  	@user = User.find(params[:id])
  end

  def edit
  	@user = User.find(params[:id])
  end

  def create
  	@user = User.new(user_params)
  	@user.save

	  if @user.save
	  	byebug
	    redirect_to profile_path
	  else
	    render 'new'
	  end
	end

	def new
		@user = User.new
	end

	def update
  @user = current_user
 
	  if @user.update(user_params)
	    redirect_to @user
	  else
	    render 'edit'
	  end
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy method: :delete

		redirect_to users_path
	end

	def profile
		@user = current_user
    @activity = Activity.find_by(params[current_user])
	end

  private

  def user_params
  	params.require(:user).permit(:first_name, :last_name, :description)
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/activities/index.html.haml
activities index.html.haml
.center


  %h2 Activites
  %ul
    %li
      %h4
        - @activity.each do |f|
          %li
            = f.title.capitalize
          %li
            = f.category.capitalize
          %li
            = f.description.capitalize
          %hr
        -# = @activity.first.title
        -# = @activity.title.capitalize
        -# = @activity.category.capitalize
        -# = @activity.description.capitalize

  %h2 Your Bucket List
  %ul
    / - for 

app/views/layouts/_navbar.html.haml
.navbar-fixed
  %nav.brown.darken-2.z-depth-2
    .nav-wrapper
      %a.brand-logo{:href => root_path} Bucket List
      %a.button-collapse{"data-activates" => "mobile-demo", :href => "#"}
        %i.material-icons menu
      %ul.right.hide-on-med-and-down
        - if user_signed_in?  
          %li
            = link_to 'Home', root_path 
          %li
            = link_to 'Users', users_path        
          %li
            = link_to 'Activities',activities_path  
          %li
            %a.dropdown-button.btn.brown.darken-2.z-depth-2{"data-activates" => "dropdown1", :href => "#"}Your Profile
            %ul#dropdown1.dropdown-content
              %li
                = link_to 'Show Profile', profile_path #TODO fix path
              %li.divide
              %li
                =link_to 'Update Profile', edit_profile_path
              %li.divide
              %li
                =link_to 'Update Email/Password', edit_user_registration_path
          %li
            = link_to('Sign Out', destroy_user_session_path, :method => :delete)
        - else
          %li
            = link_to('Login', new_user_session_path)

      %ul#mobile-demo.side-nav  
        - if user_signed_in?  
          %li
            = link_to 'Home', root_path 
          %li
            = link_to 'Users', users_path 
          %li
            = link_to 'Activities', activities_path  
          %li
            = link_to('Sign Out', destroy_user_session_path, :method => :delete)
        - else
          %li
            = link_to('Login', new_user_session_path)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title BucketList

    %link{:href => "https://fonts.googleapis.com/icon?family=Material+Icons", :rel => "stylesheet"}/

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %link{rel:"stylesheet", href:"https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.1/css/materialize.min.css"}
    %script{src:"https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.1/js/materialize.min.js"}
          

  %body
    %script{:async => "async", :src => "//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-560b1c5e0934f3da"}
    = render 'layouts/navbar'
    .container
      = yield

app/views/static_pages/home.html.haml
home

app/views/users/edit.html.haml
%br
%br 
%br
%form
  .row
    .form-group.col.s6
      %label{:for => "first_name"} First Name
      %input#exampleInputName1.formcontrol{:placeholder => "First Name", :type => "text"}
    .form-group.col.s6
      %label{:for => "last_name"} Last Name
      %input#exampleInputUsername1.formcontrol{:placeholder => "Last Name", :type => "text"}  
    Date of Birth
    %input.datepicker{:type => "date"}
    %br
    %br
    %i.material-icons.prefix mode_edit
    About You
    %textarea#icon_prefix2.materialize-textarea
    %label{:for => "icon_prefix2"}  
  .form-group
    %label{:for => "profile_picture"} Import a Profile Picture
    %input#exampleInputFile{:type => "file"} 
    %label
    %br
    %br
  %button.btn.btn-default{:type => "submit"} Update
  %br
  %br
  %br
  %br

app/views/users/edit_profile.html.haml
%br
%br 
%br
%form
  .row
    .form-group.col.s6
      %label{:for => "first_name"} First Name
      %input#exampleInputName1.formcontrol{:placeholder => "First Name", :type => "text"}
    .form-group.col.s6
      %label{:for => "last_name"} Last Name
      %input#exampleInputUsername1.formcontrol{:placeholder => "Last Name", :type => "text"}  
    Date of Birth
    %input.datepicker{:type => "date"}
    %br
    %br
    %i.material-icons.prefix mode_edit
    About You
    %textarea#icon_prefix2.materialize-textarea
    %label{:for => "icon_prefix2"}  
  .form-group
    %label{:for => "profile_picture"} Import a Profile Picture
    %input#exampleInputFile{:type => "file"} 
    %label
    %br
    %br
  %button.btn.btn-default{:type => "submit"} Update
  %br
  %br
  %br
  %br

app/views/users/index.html.haml
user index.html.haml
.center


  %h2 Users
  %ul
    %li
      %h4
        - @user.each do |f|
          %li
            = f.first_name.capitalize
            = f.last_name.capitalize
          %li
            = f.description.capitalize
          %hr
        -# = @activity.first.title
        -# = @activity.title.capitalize
        -# = @activity.category.capitalize
        -# = @activity.description.capitalize

app/views/users/profile.html.haml
.center
  %ul
    %li
      %h2
        = current_user.first_name.capitalize
        = current_user.last_name.capitalize
    %li
      = current_user.description.capitalize

  %h2 Your Bucket List
  %ul
    / - for 

app/views/users/show.html.haml
Show All Users